import { Button, VerticalBox } from "std-widgets.slint";

import "../fonts/NotoSansCJK-VF.otf.ttc";
import "../fonts/NotoEmoji-VariableFont_wght.ttf";

export AppWindow := Window {
    default-font-family: "Noto Sans";
    property<int> counter: 42;
    callback request-increase-value();
    VerticalBox { 
        Text {
            text: "Counter: \{counter}";
        }
        Button {
            text: "中文测试，增加数值，emoji测试，😀";
            clicked => { 
                request-increase-value();
            }
        }
     }
}
